### ISSUE TITLE
Ch03 certificate has expired

### ISSUE THREAD

**Issue by CRMacPherson** [sixeyed/diamol#22]
Hello,

Have the following error in container's logs for ch03:
```
** web-ping ** Pinging: blog.sixeyed.com; method: HEAD; 3000ms intervals
Making request number: 1; at 1604586506199
{ Error: certificate has expired
at TLSSocket.onConnectSecure (_tls_wrap.js:1055:34)
at TLSSocket.emit (events.js:198:13)
at TLSSocket._finishInit (_tls_wrap.js:633:8) code: 'CERT_HAS_EXPIRED' }
Making request number: 2; at 1604586509201
{ Error: certificate has expired
at TLSSocket.onConnectSecure (_tls_wrap.js:1055:34)
at TLSSocket.emit (events.js:198:13)
at TLSSocket._finishInit (_tls_wrap.js:633:8) code: 'CERT_HAS_EXPIRED' }
Making request number: 3; at 1604586512205
```

Using WSL2 on Win10 Home with Ubuntu 20.04.

Thanks!

**Comment by sixeyed** [comment]
This is because the SSL cert for my blog had expired! So I guess the tool is useful 👍 

Fixed now.

**Comment by CRMacPherson** [comment]
Yes! Pinging Google worked, thankfully I don't have to contact them ;)
... and, you mean your readers are useful too right?
btw, thanks for the great book!

**Comment by sixeyed** [comment]
Thank you :)
